/pixel_vision:
  ros__parameters:
    tf:
      trans:
        x: -0.065
        y: 0.013
        z: -0.093
      rot:
        roll: 0.0
        pitch: 3.14
        yaw: -1.57
    px_per_meter: 6036.74540683
